# Generated by Django 6.0.3 on 2026-03-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='new', max_length=20),
        ),
    ]
