# Generated by Django 5.2.17 on 2026-09-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_audiofile_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audiofile",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="audiofile",
            name="kind",
            field=models.CharField(
                choices=[
                    ("source", "Исходник"),
                    ("stem", "Дорожка"),
                    ("master", "Мастер"),
                    ("vocal_take", "Вокальный дубль"),
                ],
                default="source",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="track",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="RenderJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("overrides", models.JSONField(blank=True, default=dict)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("spec", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Обрабатывается"),
                            ("done", "Готово"),
                            ("error", "Ошибка"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("stage", models.CharField(blank=True, max_length=40)),
                ("progress", models.IntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, max_length=100)),
                (
                    "master",
                    models.FileField(blank=True, null=True, upload_to="renders/"),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="render_jobs",
                        to="core.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lyrics", models.JSONField(blank=True, default=dict)),
                ("lyric_sheet", models.TextField(blank=True)),
                ("chords", models.JSONField(blank=True, default=list)),
                ("chord_chart", models.TextField(blank=True)),
                ("tabs", models.JSONField(blank=True, default=dict)),
                ("key", models.CharField(blank=True, max_length=20)),
                ("tempo", models.FloatField(blank=True, null=True)),
                ("tuning", models.CharField(blank=True, max_length=30)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="core.renderjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("file", models.FileField(upload_to="stems/")),
                ("source", models.CharField(default="generated", max_length=20)),
                ("peak_db", models.FloatField(blank=True, null=True)),
                ("rms_db", models.FloatField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stems",
                        to="core.renderjob",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VocalTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_file", models.FileField(upload_to="takes/")),
                (
                    "processed_file",
                    models.FileField(
                        blank=True, null=True, upload_to="takes/processed/"
                    ),
                ),
                (
                    "mixed_file",
                    models.FileField(blank=True, null=True, upload_to="takes/mixed/"),
                ),
                ("style", models.CharField(default="rap", max_length=20)),
                ("gender", models.CharField(default="male", max_length=10)),
                ("target_gender", models.CharField(blank=True, max_length=10)),
                ("autotune", models.FloatField(blank=True, null=True)),
                ("gain_db", models.FloatField(default=-3.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Обрабатывается"),
                            ("done", "Готово"),
                            ("error", "Ошибка"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("notes", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vocal_takes",
                        to="core.renderjob",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocal_takes",
                        to="core.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
