# Generated by Django 5.2.17 on 2026-09-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_payment_subscription_usagerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagerecord",
            name="kind",
            field=models.CharField(
                choices=[
                    ("charge", "Списание"),
                    ("refund", "Возврат"),
                    ("cover", "Генерация кавера"),
                ],
                default="charge",
                max_length=10,
            ),
        ),
    ]
